"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrafficSide = exports.JunctionType = exports.ManeuverType = void 0;
var ManeuverType;
(function (ManeuverType) {
    ManeuverType[ManeuverType["NoTurn"] = 0] = "NoTurn";
    ManeuverType[ManeuverType["LeftTurn"] = 1] = "LeftTurn";
    ManeuverType[ManeuverType["RightTurn"] = 2] = "RightTurn";
    ManeuverType[ManeuverType["StraightAhead"] = 3] = "StraightAhead";
    ManeuverType[ManeuverType["UTurn"] = 4] = "UTurn";
    ManeuverType[ManeuverType["FollowRoad"] = 5] = "FollowRoad";
    ManeuverType[ManeuverType["EnterRoundabout"] = 6] = "EnterRoundabout";
    ManeuverType[ManeuverType["ExitRoundabout"] = 7] = "ExitRoundabout";
    ManeuverType[ManeuverType["OffRamp"] = 8] = "OffRamp";
    ManeuverType[ManeuverType["OnRamp"] = 9] = "OnRamp";
    ManeuverType[ManeuverType["ArriveEndOfNavigation"] = 10] = "ArriveEndOfNavigation";
    ManeuverType[ManeuverType["StartRoute"] = 11] = "StartRoute";
    ManeuverType[ManeuverType["ArriveAtDestination"] = 12] = "ArriveAtDestination";
    ManeuverType[ManeuverType["KeepLeft"] = 13] = "KeepLeft";
    ManeuverType[ManeuverType["KeepRight"] = 14] = "KeepRight";
    ManeuverType[ManeuverType["Enter_Ferry"] = 15] = "Enter_Ferry";
    ManeuverType[ManeuverType["ExitFerry"] = 16] = "ExitFerry";
    ManeuverType[ManeuverType["ChangeFerry"] = 17] = "ChangeFerry";
    ManeuverType[ManeuverType["StartRouteWithUTurn"] = 18] = "StartRouteWithUTurn";
    ManeuverType[ManeuverType["UTurnAtRoundabout"] = 19] = "UTurnAtRoundabout";
    ManeuverType[ManeuverType["LeftTurnAtEnd"] = 20] = "LeftTurnAtEnd";
    ManeuverType[ManeuverType["RightTurnAtEnd"] = 21] = "RightTurnAtEnd";
    ManeuverType[ManeuverType["HighwayOffRampLeft"] = 22] = "HighwayOffRampLeft";
    ManeuverType[ManeuverType["HighwayOffRampRight"] = 23] = "HighwayOffRampRight";
    ManeuverType[ManeuverType["ArriveAtDestinationLeft"] = 24] = "ArriveAtDestinationLeft";
    ManeuverType[ManeuverType["ArriveAtDestinationRight"] = 25] = "ArriveAtDestinationRight";
    ManeuverType[ManeuverType["UTurnWhenPossible"] = 26] = "UTurnWhenPossible";
    ManeuverType[ManeuverType["ArriveEndOfDirections"] = 27] = "ArriveEndOfDirections";
    ManeuverType[ManeuverType["RoundaboutExit1"] = 28] = "RoundaboutExit1";
    ManeuverType[ManeuverType["RoundaboutExit2"] = 29] = "RoundaboutExit2";
    ManeuverType[ManeuverType["RoundaboutExit3"] = 30] = "RoundaboutExit3";
    ManeuverType[ManeuverType["RoundaboutExit4"] = 31] = "RoundaboutExit4";
    ManeuverType[ManeuverType["RoundaboutExit5"] = 32] = "RoundaboutExit5";
    ManeuverType[ManeuverType["RoundaboutExit6"] = 33] = "RoundaboutExit6";
    ManeuverType[ManeuverType["RoundaboutExit7"] = 34] = "RoundaboutExit7";
    ManeuverType[ManeuverType["RoundaboutExit8"] = 35] = "RoundaboutExit8";
    ManeuverType[ManeuverType["RoundaboutExit9"] = 36] = "RoundaboutExit9";
    ManeuverType[ManeuverType["RoundaboutExit10"] = 37] = "RoundaboutExit10";
    ManeuverType[ManeuverType["RoundaboutExit11"] = 38] = "RoundaboutExit11";
    ManeuverType[ManeuverType["RoundaboutExit12"] = 39] = "RoundaboutExit12";
    ManeuverType[ManeuverType["RoundaboutExit13"] = 40] = "RoundaboutExit13";
    ManeuverType[ManeuverType["RoundaboutExit14"] = 41] = "RoundaboutExit14";
    ManeuverType[ManeuverType["RoundaboutExit15"] = 42] = "RoundaboutExit15";
    ManeuverType[ManeuverType["RoundaboutExit16"] = 43] = "RoundaboutExit16";
    ManeuverType[ManeuverType["RoundaboutExit17"] = 44] = "RoundaboutExit17";
    ManeuverType[ManeuverType["RoundaboutExit18"] = 45] = "RoundaboutExit18";
    ManeuverType[ManeuverType["RoundaboutExit19"] = 46] = "RoundaboutExit19";
    ManeuverType[ManeuverType["SharpLeftTurn"] = 47] = "SharpLeftTurn";
    ManeuverType[ManeuverType["SharpRightTurn"] = 48] = "SharpRightTurn";
    ManeuverType[ManeuverType["SlightLeftTurn"] = 49] = "SlightLeftTurn";
    ManeuverType[ManeuverType["SlightRightTurn"] = 50] = "SlightRightTurn";
    ManeuverType[ManeuverType["ChangeHighway"] = 51] = "ChangeHighway";
    ManeuverType[ManeuverType["ChangeHighwayLeft"] = 52] = "ChangeHighwayLeft";
    ManeuverType[ManeuverType["ChangeHighwayRight"] = 53] = "ChangeHighwayRight";
})(ManeuverType = exports.ManeuverType || (exports.ManeuverType = {}));
var JunctionType;
(function (JunctionType) {
    JunctionType[JunctionType["Intersection"] = 0] = "Intersection";
    JunctionType[JunctionType["Roundabout"] = 1] = "Roundabout";
})(JunctionType = exports.JunctionType || (exports.JunctionType = {}));
var TrafficSide;
(function (TrafficSide) {
    TrafficSide[TrafficSide["Right"] = 0] = "Right";
    TrafficSide[TrafficSide["Left"] = 1] = "Left";
})(TrafficSide = exports.TrafficSide || (exports.TrafficSide = {}));
